apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: hello-robot
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: localhost/hello-robot-subscriber:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      restartPolicy: Always
